### ISSUE TITLE
[CRASH] crashes on launch with AdventureZ

### ISSUE THREAD

**Issue by nickademas** [googleooer/AnvilFix-issues#1]
https://modrinth.com/mod/adventurez
[latest.log](https://github.com/googleooer/AnvilFix-issues/files/12577752/latest.log)

**Comment by FrostBird347** [comment]
I am also experiencing this bug without AdventureZ installed.
In my case, it's being triggered by Create:

`
[main/ERROR]: Mixin apply for mod porting_lib_base failed porting_lib_base.mixins.json:common.AnvilMenuMixin from mod porting_lib_base -> net.minecraft.class_1706: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("STORE" ordinal=-1 index=-1) on net/minecraft/class_1706::port_lib$grabEnchantedState with priority 1000 cannot inject into net/minecraft/class_1706::method_24928()V merged by com.googlerooeric.anvilfix.mixin.screen.AnvilScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.AnvilMenuMixin from mod porting_lib_base -> Prepare Injections ->  -> localvar$zzf000$porting_lib_base$port_lib$grabEnchantedState(Z)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("STORE" ordinal=-1 index=-1) on net/minecraft/class_1706::port_lib$grabEnchantedState with priority 1000 cannot inject into net/minecraft/class_1706::method_24928()V merged by com.googlerooeric.anvilfix.mixin.screen.AnvilScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.AnvilMenuMixin from mod porting_lib_base -> Prepare Injections ->  -> localvar$zzf000$porting_lib_base$port_lib$grabEnchantedState(Z)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at ...
`

**Comment by GeekyBakerBen** [comment]
Seconded, I get the same issue, via the porting_lib incompatibility, which seems to be used in a number of other mods, including Create. I really hope this can get resolved as on paper this mod sounds like the best anvil fix mod out there!

> [Porting Lib Base](https://github.com/Fabricators-of-Create/Porting-Lib) is conflicting with [AnvilFix](#).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("STORE" ordinal=-1 index=-1) on net/minecraft/class_1706::port_lib$grabEnchantedState with priority 1000 cannot inject into net/minecraft/class_1706::method_24928()V merged by com.googlerooeric.anvilfix.mixin.screen.AnvilScreenHandlerMixin with priority 1000 [PREINJECT Applicator Phase -> porting_lib_base.mixins.json:common.AnvilMenuMixin from mod porting_lib_base -> Prepare Injections ->  -> localvar$zze000$porting_lib_base$port_lib$grabEnchantedState(Z)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_2246.<clinit>(class_2246.java:554)
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

## Game info
Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.7

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
